### ISSUE TITLE
Failing to find npm package after install

### ISSUE THREAD

**Issue by TimHill83** [odroe/vue-heroicons#5]
Hi, please excuse me if I'm doing the wrong thing posting here- I'm quite new to Vue, Webpack and npm, so this could definitely be my fault.

I've run `npm i @bytegem/vue-heroicons -S`  as directed, and npm install appears to go fine.

When importing into my project and trying to run serve, I get the following:

```
this dependency was not found:

* @bytegem/vue-heroicons in ./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/babel-loader/lib??ref--1-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/uk-lettings-1/before-after.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @bytegem/vue-heroicons
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'     
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'     
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```
I have tried uninstalling and reinstalling, but no success

I was originally running in Gridsome, and thought it might relate to that, so tried in a plain vue test project with the same result. My main.js is as follows:
```js
import Vue from "vue";
import App from "./App.vue";
import Heroicons from "@bytegem/vue-heroicons";
Vue.use(Heroicons);
Vue.config.productionTip = false;

new Vue({
  render: (h) => h(App),
}).$mount("#app");
```

I've also tried other npm packages, which all seem to be working fine.  I'm stumped.

Is anyone else having this problem?  I'm running this through VSCode on Windows.

**Comment by medz** [comment]
@TimHill83 
Thank you for your feedback. This project was built during the Vue2 period, and now Vue 3 has been released, we do not recommend using this package.

You can use the official package of `heroicons` (note that this is a Vue 3 only):
```bash
npm i heroicons --save
```

If you still want to use this package, you can try to run `npm i --save @bytegem/heroicons`

The general reason why you have this problem is that NPM may not parse the command correctly in the Windows environment.

Reminder: This package will enter the archive and no longer update state soon. We will try the ease of use of heroicons, and if the ease of use is poor, we will enable the project again.

Thanks!
